### PR TITLE
Style/WordArray

### PR DESCRIPTION
**Pull request by Xorima**
### Description

We should not fail cookstyle when using our examples

### Issues Resolved

[List any existing issues this PR resolves]

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by damacus** [comment]
Whilst this is technically correct. The documentation shouldn't have ruby in it, IMHO. 

But, please eel free to disagree on this with me and change my mind!

**Comment by Xorima** [comment]
I guess we are showing what the default is here, however I just copied and pasted it when building out my recipe and it failed cookstyle, your call mate

Also we should fix source centos-7 eventually ...

**Comment by JohnRoesler** [comment]
I have to agree with Dan - I think we should keep the ruby syntax our of the readme

**Comment by Xorima** [comment]
Ok guys :) closing

**Pull request closed without merging**
