### PR TITLE
add platforms provided by service resource

### PR DESCRIPTION
**Pull request by JohnRoesler**
### Description

Adds provides to the service resource
### Issues Resolved

closes: #355 
### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by JohnRoesler** [comment]
@tas50 is this done right? Should all the custom resources have provides? Wondering if we actually need this because we only have one service resource. My understanding is the provides would be beneficial if we had different service resources for different OS-es, like systemd vs. init, or just differences between a Centos or Debian service?

**Comment by damacus** [comment]
I think we only need this on the service resource, as it's only that one that has restrictions. 

But then again now we're only supporting systemd systems..? Do we need this at all

**Comment by JohnRoesler** [comment]
we don't need this anymore - we only have systemd service, so no need to provide a `haproxy_service` that maps to `haproxy_service_systemd`

**Pull request closed without merging**
