### PR TITLE
adding acl and userlist, fixes #207

### LINKED ISSUE #207: Feature: support userlist
### Cookbook version
4.0.2

### Chef-client version
12.19.36

### Platform Details
CentOS 6

### Scenario:
Create userlist blocks:
```
userlist stats-auth
    group admin    users admin
    user  admin    insecure-password AdMiN123
    group readonly users haproxy
    user  haproxy  insecure-password haproxy

backend stats_auth
    stats enable
    acl AUTH       http_auth(stats-auth)
    acl AUTH_ADMIN http_auth_group(stats-auth) admin
    stats http-request auth unless AUTH
    stats admin if AUTH_ADMIN
```

### Steps to Reproduce:
Feature request. The backend or listen providers can handle via `extra_options` the additional stats directives, or in the case of `haproxy_config_default` via the hash.

### Expected Result:
Create the above desired configuration without having to customize a template

Reference: https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#3.4

### Actual Result:
N/A

### PR DESCRIPTION
**Pull request by rshade**
### Description
Adding userlist and acl resources

### Issues Resolved
#207 
### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by damacus** [comment]
This worries me slightly, in usage and possible blatting current resources accidently. 

But if we can write a bunch of tests to exercise this I'll be super happy with it.

**Comment by rshade** [comment]
absolutely, I am going to put quite a few tests in here. I am seeing this as 4.1 possible

**Comment by mengesb** [comment]
acceptance criteria:

```ruby
haproxy_userlist 'mylist' do
  group 'G1' => 'users tiger,scott',
        'G2' => 'users xdb,scott'
  user  'tiger' => 'password $6$k6y3o.eP$JlKBx9za9667qe4(...)xHSwRv6J.C0/D7cV91',
        'scott' => 'insecure-password elgato',
        'xdb' => 'insecure-password hello'
end
```

Results in the following configuration:
```
userlist L1
  group G1 users tiger,scott
  group G2 users xdb,scott

  user tiger password $6$k6y3o.eP$JlKBx9za9667qe4(...)xHSwRv6J.C0/D7cV91
  user scott insecure-password elgato
  user xdb insecure-password hello
```

**Comment by teknofire** [comment]
So I have two thoughts on possible syntax for the haproxy_acl resource

### first possibility
make use of the name property to hold the rule, since this will generally be pretty unique
section and section_name seem cumbersome but not sure what would be a better name
but quickly explodes into a lot of extra typing or doing some sort of each over an array of acls

```
haproxy_acl 'gina_host hdr(host) -i foo.bar.com' do
  section 'frontend'
  section_name 'http'
end

haproxy_use_backend 'gina if gina_host' do
  section 'frontend'
  section_name 'http'
end
```

### second posibility
don't use name for the rule, but provide the array of acls to add to the section, implementing adding the rules to the resource variables would just require updating it do something like `variables[new_resource.section][new_resource.section_name]['acl'] += Array(new_resource.acls)`


```
haproxy_acl 'acls for frontend:http' do
  section 'frontend'
  section_name 'http'
  acls [
    'kml_request path_reg -i /kml/',
    'bbox_request path_reg -i /bbox/',
    'gina_host hdr(host) -i foo.bar.com',
    'rrhost_host hdr(host) -i dave.foo.bar.com foo.foo.com',
    'tile_host hdr(host) -i dough.foo.bar.com',
  ]
end

haproxy_use_backend 'use_backends for frontend:http' do
  section 'frontend'
  section_name 'http'  
  use_backends [
    'gina if gina_host',
    'rrhost if rrhost_host',
    'abuser if source_is_abuser',
    'tiles_public if tile_host'
  ]
end
```

For complete examples of how these two thoughts could be applied to config-2 tests see:

https://gist.github.com/teknofire/c6969955bfeafa903629b30f4575d93c

**Comment by damacus** [comment]
LGTM 🌮

**Comment by mengesb** [comment]
LGTM too; did we remove the ACL bits ??? If so I can update the topic of the issue so that it matches

**Pull request merged**
