### PR TITLE
Reload haproxy configuration on changes

### PR DESCRIPTION
**Pull request by obazoud**

### CODE REVIEW

**Comment by shortdudey123** [comment]
Partial dupe of https://github.com/sous-chefs/haproxy/pull/99

**Comment by obazoud** [comment]
@shortdudey123 yes but not yet merged!

**Comment by tas50** [comment]
I know at one point there was a reason for this. Not everything could be changed with a reload. It's worth finding out if a complete change of the config works with a reload.

**Comment by rshade** [comment]
it looks like it should clean it up: 
```
       -sf <pidlist>
              Send FINISH signal to the pids in pidlist after startup. The processes which receive this signal will wait for  all  sessions  to  finish  before
              exiting. This option must be specified last, followed by any number of PIDs. Technically speaking, SIGTTOU and SIGUSR1 are sent
       - SIGUSR1
              Tells the daemon to stop all proxies and exit once all sessions are closed. It is often referred to as the "soft-stop" signal.

       - SIGTTOU
              Tells the daemon to stop listening to all sockets. Used internally by -sf and -st.
```

**Comment by rshade** [comment]
it looks like https://github.com/horms/haproxy/blob/master/src/haproxy-systemd-wrapper.c#L200, does the graceful restart by default. I am going to merge this into dev_2

**Pull request merged**
