### PR TITLE
Customize logging destination

### PR DESCRIPTION
**Pull request by erinn**
### Description

This allows logging to be fully configurable.

### Issues Resolved

None

### Contribution Check List

- [x] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by damacus** [comment]
:shipit:

**Comment by damacus** [comment]
Thanks for the contribution! 

We could do with a simple test to see if this puts the right config on disk please and we'll ship the cookbook as soon as that's done.

**Comment by erinn** [comment]
I would happily but honestly right now I don't really understand where to put the tests. Your dokken file references inspec but that doesn't seem to be used. you have serverspec and bats, and well honestly I am confused about how this all comes together.

**Comment by damacus** [comment]
No problem, if you jump onto the sous-chefs channel on the chef community slack we'll give you a hand understanding it. It might be time to add a testing.md for the dokken stuff. However regarding inspec and bats, that's another reason why we are doing the rewrite.

**Pull request merged**
