### PR TITLE
Support Array value for extra_options entries.

### PR DESCRIPTION
**Pull request by emiellohr**
### Description

Support Array value for extra_options entries to write multiple extra options entries with the same key to the config.

### Issues Resolved

245

### Contribution Check List
Test suite failed @ my end. So no test is included. :-(
- [ ] All tests pass.
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/haproxy/246)

### CODE REVIEW

**Comment by damacus** [comment]
*[README.md, line 13 at r1](https://reviewable.io:443/reviews/sous-chefs/haproxy/246#-KoGi83G6IJg_pCuLoQG:-KoGi83G6IJg_pCuLoQH:b1s6wjy) ([raw file](https://github.com/sous-chefs/haproxy/blob/8f8ed78b47053a111ebf77d3f62472561f952777/README.md#L13)):*
> ```Markdown
> ### Platforms
> 
> - Ubuntu 12.04+, Ubuntu 14.04+, Ubuntu 16.04
> ```

We can probably just drop 12.04 here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sous-chefs/haproxy/246)*

**Comment by damacus** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sous-chefs/haproxy/246)*

**Comment by damacus** [comment]
Sticking this in one of the test would probably do: 
```ruby
 extra_options(
    'redirect' => [
     'code 301 prefix / if acl1',
     'scheme https if !acl_2'
])

```

**Comment by rshade** [comment]
@emiellohr can you throw up the test you have and we can help you fix it?

**Comment by rshade** [comment]
@emiellohr can you do a merge from master, throw in your tests? I will put it into a dev branch here and help fix it.

**Comment by rshade** [comment]
@emiellohr thank you for your contribution, I have merged it via another branch.

**Pull request closed without merging**
