### PR TITLE
Frontend use backend

### PR DESCRIPTION
**Pull request by JohnRoesler**
### Description
Current cookbook `haproxy.cfg` template outputs the `use_backend` rules before the `http-request` rules. These rules per haproxy config validation, should occur after the `use_backend` rules.
```
$ sudo haproxy -c -V -f /etc/haproxy/haproxy.cfg
[WARNING] ... : parsing [/etc/haproxy/haproxy.cfg:50] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
```

This PR just moves the `use_backend` rules after the `extra_options` in the template erb

### Issues Resolved

fixes: #313 

### Contribution Check List

Seeking help on the tests. I am probably being dense, but haven't been able to run tests locally. Attempted following the [linked testing documentation](https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD). Could anyone share like a quick list of what it takes to run the tests? The `chef exec bundle install` complains that I don't have a `Gemfile` and the `delivery local unit` complains that I don't have a `local` file.

- [x] All tests pass.
- [x] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by JohnRoesler** [comment]
@damacus What do you think about something like this PR that only sets the `http-request` and `http-response` rules above the `use_backend` which is what the haproxy config is actually only complaining about?

First attempt PR: https://github.com/sous-chefs/haproxy/pull/314

**Comment by damacus** [comment]
Should http-request always basically come last?  If so this is sweet.

**Comment by JohnRoesler** [comment]
http-request rules should always come before `use_backend`. Did I get my if unless logic right? I thought it was sweet, much better than attempt #1.

**Comment by rshade** [comment]
@JohnRoesler sorry for the delay, is it possible to test for this?

**Comment by JohnRoesler** [comment]
@rshade no worries! Good question, I was struggling to get tests to run, so I admit I didn't attempt adding one. I tried following the linked chef testing standard. I'd be happy to add a test, but may need some assistance with where to start.

**Comment by rshade** [comment]
you could probably do an inspect test: https://www.inspec.io/docs/reference/resources/command/, that checks for that warning. I think that might be good enough to prove it works.

**Comment by damacus** [comment]
@rshade we probably actually want a chefspec test if we can help it (or move the other generic test to spec tests to speed up the run).

**Comment by damacus** [comment]
@JohnRoesler if you drop in on #sous-chef on the chef community slack we can talk you through it. :)

**Comment by JohnRoesler** [comment]
@damacus @rshade mind taking a look this PR again?

**Comment by damacus** [comment]
Usually we'd bump as a seperate process. But this is fine. I don't think that unit test is actually testing the ordering in the file 🤔

**Comment by JohnRoesler** [comment]
Awesome!

**Pull request merged**
