### PR TITLE
add resolver resource

### LINKED ISSUE #240: Top level resolvers config support
Would be nice to support DNS resolvers configuration.

E.g. https://cbonte.github.io/haproxy-dconv/configuration-1.6.html#5.3.2

### PR DESCRIPTION
**Pull request by troyready**
### Description

Allows `resolvers` to be specified

### Issues Resolved

#240 

### Contribution Check List

- [x] All tests pass.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/haproxy/241)

### CODE REVIEW

**Comment by troyready** [comment]
@damacus sure thing, should be added now.

**Comment by rshade** [comment]
can you add a line here: https://github.com/sous-chefs/haproxy/blob/master/.travis.yml#L42

**Comment by rshade** [comment]
looks good by the way

**Comment by troyready** [comment]
@rshade got it, thanks -- it's been added

**Comment by rshade** [comment]
@troyready thanks man. Looks great.

**Pull request merged**
