### PR TITLE
Update haproxy_install.md

### PR DESCRIPTION
**Pull request by derekgroh**
### Description

Updates documentation to match changes made #457 

### Issues Resolved

None

### Contribution Check List

N/A documentation

### CODE REVIEW

**Comment by bmhughes** [comment]
Thanks for the PR @derekgroh! If you sort out the trailing space mdl error we can get this merged, also could you do me a favour and drop the `nil`s I missed from the allowed values as well please as they don't really make sense to be there.

**Comment by derekgroh** [comment]
@bmhughes Believe I got all the `nils` you wanted.

**Comment by bmhughes** [comment]
> @bmhughes Believe I got all the `nils` you wanted.

Yes that looks ideal, thanks for that. Just stick and entry in the changelog under unreleased and we should be good to go.

**Comment by derekgroh** [comment]
Really? Thought documentation wasn't included in the changelog, did that change or am I thinking another project?

**Comment by bmhughes** [comment]
Doc changes have always been in there as far as I know so got to be something else.

**Review by bmhughes — APPROVED** [review]

**Comment by bmhughes** [comment]
Rather than a merge you need to drop the merge commit and rebase your branch on master. Assuming your forked repos master is up to date with this repos master (which it appears to be).

`git reset --hard HEAD^ && git rebase master`

**Pull request closed without merging**
