### PR TITLE
Test for appropriate spacing from start of line and end of line

### PR DESCRIPTION
**Pull request by JohnRoesler**
### Description

All the integration test matches are updated to include checking for correct indentation from start of the line and spacing (or lack there of ) at the end of the lines.

I used the literal space character in lieu of the `\s` whitespace character as whitespace includes line breaks, which we specifically do not want in many cases.

### Issues Resolved

closes: https://github.com/sous-chefs/haproxy/issues/228

### Contribution Check List

- [X] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by JohnRoesler** [comment]
Yep, all the tests passed. Do we know what's going on with circleci? It be nice to get that fixed up.

**Comment by damacus** [comment]
Ah ye , I'm not building PRs from forks. That should be fixed now. 


Can you push a CHANGELOG update to force it to rerun please?

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add labels to this Pull Request</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damacus** [comment]
Brill thanks caught a couple of things. 
If you're running ChefDK/Chef Workstation
`cookstyle -a` should fix that. 

Then run `chef exec delivery local all` to check the lint and unit phases are ok.

**Pull request merged**
