### PR TITLE
added compiling from source crypt support

### PR DESCRIPTION
**Pull request by Stromweld**
### Description

added compile use_libcrypt=1 support to compile command

### Contribution Check List

- [ ] All tests pass.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by Stromweld** [comment]
failure is due to chef 14 build_essential resource being built-in but metadata says it depends on build-essential cookbook.

**Comment by damacus** [comment]
Cool I'll put in a fix for build essential then get you to rebase if that's alright?

**Comment by damacus** [comment]
Thanks very much for the contribution!

**Comment by Stromweld** [comment]
thanks you

**Pull request merged**
