### PR TITLE
add missing maxconn in global

### PR DESCRIPTION
**Pull request by paulius005**
### Description

adding missing maxconn to global config. Not sure why this was missing, thought I would raise a PR rather than an issue if it is a simple fix

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/haproxy/222)

### CODE REVIEW

**Comment by rshade** [comment]
@paulius005 can you add in the property and update the tests?

**Comment by rshade** [comment]
@paulius005 thank you for your contribution. I am pushing into the DEV branch to fix the items.

**Comment by paulius005** [comment]
got it! Sorry for the late reply, was away from computer for the past 5 days

**Comment by rshade** [comment]
Very cool, no worries. I will try and get those items done and get you a release out.

**Pull request merged**
