### PR TITLE
Provide separate SSL pool member capability

### PR DESCRIPTION
**Pull request by dylancanfield**
### Description

This change allows different members to be defined in the SSL pool via the node['haproxy']['ssl_members'] attribute . The default behavior is to use the node['haproxy']['members'] attribute, if no node['haproxy']['ssl_members'] are defined.

### Contribution Check List

- [ *] All tests pass.
- [ ] New functionality includes testing.
- [ *] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by shoekstra** [comment]
Hi!

I'm not understanding what extra these two attributes add, could you provide a use case please?  

When would you use these instead of `['haproxy']['members']` and `['haproxy']['pool_members_option']`?

**Comment by dylancanfield** [comment]
Use case examples:
1) You have two different applications, one serves HTTP responses and one serves HTTPS responses.
2) Provide SSL/TLS termination for an application, like Varnish, and also provide load balancing to backend servers, for example Apache HTTPD machines. In this example, Varnish members would be the ssl_pool_members and HTTPD members would be the pool_members.

**Comment by shoekstra** [comment]
I've been trying to understand how that would work (and how to make this work), but I don't believe it is possible by adding those two attributes.

I know there are more properties involved, but to simplify things, if I had this in my attributes file:

```
default['haproxy']['members'] = 'http-server1'
default['haproxy']['ssl_members'] = 'ssl-server1'
```

`member_pool` in `recipes/manual.rb` will always be `ssl-server1`.  Because of the or operator (`||`),  `node['haproxy']['ssl_members']` will always take precedence.  Setting both attributes won't create two member pools, instead the one will override the other. 

If I didn't have `node['haproxy']['ssl_members']`, then `node['haproxy']['members']` is used. and as only one pool will be created, effectively you have two attributes used to configure the same property.

Similarly instead of using `node['haproxy']['ssl_pool_members_option']`, I could use `node['haproxy']['pool_members_option']` to specify SSL options.

I think if you wanted to have multiple frontends and backends, what you'd really want is to have a recipe that iterates over `haproxy_lb` rather than try make a generic recipe like `recipes/manual.rb` do it for you.

**Comment by rshade** [comment]
@dylancanfield thank you for your PR man. We were able to get 4.0 out today.

**Pull request closed without merging**
