### PR TITLE
Improved rendering of the configuration file

### PR DESCRIPTION
**Pull request by Dreeg**
Improved rendering of the configuration file.
There were several empty lines in the generated file.

### CODE REVIEW

**Comment by rshade** [comment]
why the multi-line on all the ifs?

**Comment by Dreeg** [comment]
Hi rshade,
multi line on all conditional (if and unless) is required to avoid the empty line in the file if the condition is 'False'.

**Comment by rshade** [comment]
cool can you update the changelog? Yeah, source download has been a pita this morning.

**Comment by Dreeg** [comment]
Sure! Just a moment.
In the next few days I will replicate the PR # 174 on the new code and implement a bit 'README.md' if I can find time.

**Comment by rshade** [comment]
awesome, thanks man.

**Comment by Dreeg** [comment]
Done

**Comment by rshade** [comment]
thanks man.

**Pull request merged**
